### ISSUE TITLE
[Feature] When will quantization-aware-training be supported

### ISSUE THREAD

**Issue by hasuoshenyun** [open-mmlab/mmrazor#108]
### Describe the feature

I see that QAT will be supported in the future. When will it be released? 
Besides, is the quantization method mainly used pytorch's own method?

**Comment by humu789** [comment]
We will realease it within this year,  the exact timing is hard to pin down because of manpower shortage.
Some pytorch's basic APIs may be used, but quantization algorithms will mainly be  developed by ours.
