### ISSUE TITLE
Any plan for OFA or BigNAS implementation?

### ISSUE THREAD

**Issue by raymon-tian** [open-mmlab/mmrazor#11]
Hi, thanks for your hard working.
Can I know if there are some plans for OFA or BigNAS algorithm implementation?

**Comment by HIT-cwh** [comment]
> Hi, thanks for your hard working. Can I know if there are some plans for OFA or BigNAS algorithm implementation?

Actually we have reserved interfaces for OFA. The Progressive Shrinking in OFA can be implemented by setting different `space_mask`  in different training stages. 
OFA is in our plan but it could be a long time. And we wil appreciate it if you can contribute to us.
By the way, the definition of `space_mask` can be find [here](https://github.com/open-mmlab/mmrazor/blob/15b5848e27df15ecb0c2a17733c17d45b42d8410/mmrazor/models/mutables/mutable_module.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L98) and it can be used like [this](https://github.com/open-mmlab/mmrazor/blob/15b5848e27df15ecb0c2a17733c17d45b42d8410/mmrazor/models/mutators/one_shot_mutator.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L33-L36)

**Comment by raymon-tian** [comment]
> > Hi, thanks for your hard working. Can I know if there are some plans for OFA or BigNAS algorithm implementation?
> 
> Actually we have reserved interfaces for OFA. The Progressive Shrinking in OFA can be implemented by setting different `space_mask` in different training stages. OFA is in our plan but it could be a long time. And we wil appreciate it if you can contribute to us. By the way, the definition of `space_mask` can be find [here](https://github.com/open-mmlab/mmrazor/blob/15b5848e27df15ecb0c2a17733c17d45b42d8410/mmrazor/models/mutables/mutable_module.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L98) and it can be used like [this](https://github.com/open-mmlab/mmrazor/blob/15b5848e27df15ecb0c2a17733c17d45b42d8410/mmrazor/models/mutators/one_shot_mutator.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L33-L36)

thanks for your reply.

**Comment by pppppM** [comment]
If you are interested in reproducing OFA or BigNAS, welcome to make a PR, and we can develop it together. @raymon-tian
