### ISSUE TITLE
KD

### ISSUE THREAD

**Issue by wwjwy** [open-mmlab/mmrazor#118]
Can the knowledge distillation algorithm be used for classification, detection and segmentation tasks by modifying the distiller components and the teacher model student model?For example, the wsld algorithm  used for object detection and image segmentation, is it possible?
Thanks!

**Comment by pppppM** [comment]
I think the `WSLD` is just suitable for classification or segmentation.
If you want to use it in segmentation, you need to modify some codes.
Currently, the `WSLD` in MMRazor can only handle 2-dim inputs.
