### ISSUE TITLE
Any plan for supporting MMEditing?[Feature]

### ISSUE THREAD

**Issue by HuaZheLei** [open-mmlab/mmrazor#12]
Thanks for your excellent job. I'd like to know if you have any plan to support MMEditing.

**Comment by pppppM** [comment]
We will not add editing-related compression algorithms in a short time, but MMRazor can quickly adapt to MMEditing. If you are interested in reproducing editing-related algorithms based on MMRazor, welcome to make a PR, and we will develop it with you
