### ISSUE TITLE
Knowledge Distillataion for mmdetection model 2

### ISSUE THREAD

**Issue by kdh-awraw1019** [open-mmlab/mmrazor#123]
_base_ = [
    '../../_base_/datasets/mmdet/coco_detection.py',
    '../../_base_/schedules/mmdet/schedule_1x.py',
    '../../_base_/mmdet_runtime.py'
]

##################### model settings
student = dict(
    type='mmdet.YOLOF',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    neck=dict(
        type='DilatedEncoder',
        in_channels=2048,
        out_channels=512,
        block_mid_channels=128,
        num_residual_blocks=4),
    bbox_head=dict(
        type='YOLOFHead',
        num_classes=2,
        in_channels=512,
        reg_decoded_bbox=True,
        anchor_generator=dict(
            type='AnchorGenerator',
            ratios=[1.0],
            scales=[1, 2, 4, 8, 16],
            strides=[32]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1., 1., 1., 1.],
            add_ctr_clamp=True,
            ctr_clamp=32),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='GIoULoss', loss_weight=1.0)),
    ################## training and testing settings
    train_cfg=dict(
        assigner=dict(
            type='UniformAssigner', pos_ignore_thr=0.15, neg_ignore_thr=0.7),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.6),
        max_per_img=100))

teacher = dict(
    type='mmdet.YOLOF',
    backbone=dict(
        type='ResNeXt',
        depth=101,
        groups=64,
        base_width=4,
        num_stages=4,
        out_indices=(1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        style='pytorch',
        init_cfg=None),
    neck=dict(
        type='DilatedEncoder',
        in_channels=2048,
        out_channels=512,
        block_mid_channels=128,
        num_residual_blocks=4),
    bbox_head=dict(
        type='YOLOFHead',
        num_classes=2,
        in_channels=512,
        reg_decoded_bbox=True,
        anchor_generator=dict(
            type='AnchorGenerator',
            ratios=[1.0],
            scales=[1, 2, 4, 8, 16],
            strides=[32]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[.0, .0, .0, .0],
            target_stds=[1., 1., 1., 1.],
            add_ctr_clamp=True,
            ctr_clamp=32),
        loss_cls=dict(
            type='FocalLoss',
            use_sigmoid=True,
            gamma=2.0,
            alpha=0.25,
            loss_weight=1.0),
        loss_bbox=dict(type='GIoULoss', loss_weight=1.0)),
    ################### training and testing settings
    train_cfg=dict(
        assigner=dict(
            type='UniformAssigner', pos_ignore_thr=0.15, neg_ignore_thr=0.7),
        allowed_border=-1,
        pos_weight=-1,
        debug=False),
    test_cfg=dict(
        nms_pre=1000,
        min_bbox_size=0,
        score_thr=0.05,
        nms=dict(type='nms', iou_threshold=0.6),
        max_per_img=100))

################### use caffe img_norm
img_norm_cfg = dict(
    mean=[103.530, 116.280, 123.675], std=[1.0, 1.0, 1.0], to_rgb=False)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(type='RandomShift', shift_ratio=0.5, max_shift_px=32),
    dict(type='Normalize', **img_norm_cfg),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(type='Normalize', **img_norm_cfg),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img']),
        ])
]

################ optimizer by mmdetection documents
optimizer = dict(type='SGD', lr=1e-3, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict()

################### learning policy by mmdetection documents
lr_config = dict(policy='step', 
                 min_lr=1e-3,
                 # by_epoch=True,
                 warmup='linear',
                 warmup_iters=5000,
                 warmup_ratio=1.0 / 5,
                 step=1,
                 warmup_by_epoch=False)
runner = dict(type='EpochBasedRunner', max_epochs=150)
evaluation= dict(classwise=True, interval=1, metric='bbox')

#################### algorithm setting
algorithm = dict(
    type='GeneralDistill',
    architecture=dict(
        type='MMDetArchitecture',
        model=student,
    ),
    distiller=dict(
        type='SingleTeacherDistiller',
        teacher=teacher,
        teacher_trainable=False,
        components=[
            dict(
                student_module='bbox_head.cls_score',
                teacher_module='bbox_head.cls_score',
                losses=[
                    dict(
                        type='ChannelWiseDivergence',
                        name='loss_cwd_cls_head',
                        tau=1,
                        loss_weight=5,
                    )
                ])
        ]),
)

find_unused_parameters = True
log_config = dict(
    interval=50,
    hooks=[dict(type='TextLoggerHook')])

custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]

################ 

python tools/mmdet/train_mmdet.py ./configs/distill/cwd/cbox_cwd_cls_head_yolof_r101_fpn_yolof_r50_fpn_1x_coco.py --cfg-options algorithm.distiller.teacher.init_cfg.type=Pretrained algorithm.distiller.teacher.init_cfg.checkpoint=./teacher_model/yolof/epoch_115.pth

################# error message

Traceback (most recent call last):
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'init_cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/jovyan/nas/1_user/dhkyung@agilesoda.ai/checkbox_gen/mmrazor/mmrazor/models/distillers/single_teacher.py", line 35, in __init__
    self.teacher = self.build_teacher(teacher)
  File "/home/jovyan/nas/1_user/dhkyung@agilesoda.ai/checkbox_gen/mmrazor/mmrazor/models/distillers/single_teacher.py", line 71, in build_teacher
    teacher = MODELS.build(cfg)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: YOLOF: __init__() got an unexpected keyword argument 'init_cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/jovyan/nas/1_user/dhkyung@agilesoda.ai/checkbox_gen/mmrazor/mmrazor/models/algorithms/general_distill.py", line 23, in __init__
    super(GeneralDistill, self).__init__(**kwargs)
  File "/home/jovyan/nas/1_user/dhkyung@agilesoda.ai/checkbox_gen/mmrazor/mmrazor/models/algorithms/base.py", line 57, in __init__
    self._init_distiller(distiller)
  File "/home/jovyan/nas/1_user/dhkyung@agilesoda.ai/checkbox_gen/mmrazor/mmrazor/models/algorithms/base.py", line 134, in _init_distiller
    self.distiller = build_distiller(distiller)
  File "/home/jovyan/nas/1_user/dhkyung@agilesoda.ai/checkbox_gen/mmrazor/mmrazor/models/builder.py", line 35, in build_distiller
    return DISTILLERS.build(cfg)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: SingleTeacherDistiller: YOLOF: __init__() got an unexpected keyword argument 'init_cfg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/mmdet/train_mmdet.py", line 204, in <module>
    main()
  File "tools/mmdet/train_mmdet.py", line 177, in main
    algorithm = build_algorithm(cfg.algorithm)
  File "/home/jovyan/nas/1_user/dhkyung@agilesoda.ai/checkbox_gen/mmrazor/mmrazor/models/builder.py", line 20, in build_algorithm
    return ALGORITHMS.build(cfg)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/envs/mmrazor/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
TypeError: GeneralDistill: SingleTeacherDistiller: YOLOF: __init__() got an unexpected keyword argument 'init_cfg'

#################################

**Comment by pppppM** [comment]
What is your mmdet version？

**Comment by kdh-awraw1019** [comment]
My setting is 

PyTorch: 1.7.0
TorchVision: 0.8.0
OpenCV: 4.5.5
MMCV: 1.4.2
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.0
MMDetection: 2.22.0+81e0e34
mmrazor: 0.2.0

**Comment by pppppM** [comment]
Because YOLOF is not updated in time, init_cfg cannot be used.
I will contact the developers of mmdet to fix this as soon as possible.

The quick solution is to add init_cfg to the arg of YOLOF, and you can refer to YOLOX.
https://github.com/open-mmlab/mmdetection/blob/bde7b4b7eea9dd6ee91a486c6996b2d68662366d/mmdet/models/detectors/yolox.py#L18-L20

**Comment by kdh-awraw1019** [comment]
Thank you :)
