### ISSUE TITLE
Applicable Optimizers

### ISSUE THREAD

**Issue by kdh-awraw1019** [open-mmlab/mmrazor#125]
How many optimizers are applicable in mmrazor?

Those are equal about other open-mmlab projects?

**Comment by pppppM** [comment]
The usage of multiple optimizers is consistent with other OpenMMLab repos, such as MMEditing.
In MMRazor, the `Darts` algorithm is an example to use multiple optimizers.
If you want to use multi optimizers in your algorithm, you need to set `optimizer_config=None`, `use_ddp_wrapper=True` and execute `optimizer.step()` in `train_step`.
https://github.com/open-mmlab/mmrazor/blob/81e0e3452a96939f79051d67e6564dfb4d13487e/configs/nas/darts/darts_supernet_unroll_1xb64_cifar10.py#L77-L80
https://github.com/open-mmlab/mmrazor/blob/81e0e3452a96939f79051d67e6564dfb4d13487e/configs/nas/darts/darts_supernet_unroll_1xb64_cifar10.py#L94
https://github.com/open-mmlab/mmrazor/blob/81e0e3452a96939f79051d67e6564dfb4d13487e/mmrazor/models/algorithms/darts.py#L66-L70
