### ISSUE TITLE
Is it possible to change the teacher checkpoint at every epoch during the distillation process?

### ISSUE THREAD

**Issue by uzair789** [open-mmlab/mmrazor#129]
Hi,
I have a teacher model trained for 12 epochs and I have a teacher checkpoint saved for each epoch like this teacher_epoch_0.pth, teacher_epoch_1.pth....teacher_epoch_11.pth. 

When performing distillation on a student model and training it also for 12 epochs, i want to load the teacher checkpoint corresponding to the epoch number, for eg, for epoch 0, i want to use teacher_epoch_0.pth ...and so on and keep changing the teacher at every epoch.

How do i do this in the mmrazor framework? I see that I can create a MultiTeacherDistiller but it doest allow me to keep track of the epochs and keep changing the teacher's weights to build a new teacher model every epoch. Please advise. Thank you

**Comment by pppppM** [comment]
Maybe you can try to develop a hook to change the teacher's checkpoint every epoch.
There is an example to modify the drop path prob for every epoch.
https://github.com/open-mmlab/mmrazor/blob/81e0e3452a96939f79051d67e6564dfb4d13487e/mmrazor/core/hooks/drop_path_prob.py#L7-L41
