### ISSUE TITLE
[Bug] 'AutoSlim' object has no attribute 'channel_cfg'

### ISSUE THREAD

**Issue by tanghy2016** [open-mmlab/mmrazor#147]
### Describe the bug

Refer to [Pruning-Split Checkpoint(Optional)](https://mmrazor.readthedocs.io/en/latest/test.html) for the following command:

```
$ python ./tools/model_converters/split_checkpoint.py \
>   configs/pruning/autoslim/autoslim_mbv2_supernet_8xb256_ci10.py \
>   output/epoch_49.pth \
>   --channel-cfgs output/subnet_497881198.yaml,output/subnet_297081551.yaml,output/subnet_197465826.yaml
load checkpoint from local path: output/epoch_49.pth
Traceback (most recent call last):
  File "./tools/model_converters/split_checkpoint.py", line 69, in <module>
    main()
  File "./tools/model_converters/split_checkpoint.py", line 60, in main
    algorithm.channel_cfg[i])
  File "/home/tanghuayang/venv_torch/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 948, in __getattr__
    type(self).__name__, name))
AttributeError: 'AutoSlim' object has no attribute 'channel_cfg'
```

**Comment by pprp** [comment]
Refer to [document](https://mmrazor.readthedocs.io/en/latest/test.html#split-checkpoint-optional) `when you retrain a slimmable model, your command will be like --cfg-options algorithm.channel_cfg=cfg1,cfg2,cfg3`

so `--cfg-options algorithm.channel_cfg` is missing in your command.

**Comment by tanghy2016** [comment]
mentioned in the documentation:
For example, when you retrain a slimmable model, your command will be like --cfg-options algorithm.channel_cfg=cfg1,cfg2,cfg3.
**And your command here should be --channel-cfgs cfg1 cfg2 cfg3.** The order of them should be the same.
and there is no algorithm.channel_cfg in the example given.

**Comment by pprp** [comment]
Hi, tanghy2016. Maybe you can refer to [this example](https://github.com/open-mmlab/mmrazor/tree/master/configs/pruning/autoslim).

There are five steps to complete the autoslim pipeline. 

- After [step2](https://github.com/open-mmlab/mmrazor/tree/master/configs/pruning/autoslim#search-for-subnet-on-the-trained-supernet), you will get some YAML files, which represent different network structure.
- In [step3](https://github.com/open-mmlab/mmrazor/tree/master/configs/pruning/autoslim#subnet-retraining-on-imagenet),  you can choose some models with different flops such as 200M flops, 300M flops and 500M flops, and retrain them on imagenet. 
- **Note that** the YAML files used in [step4](https://github.com/open-mmlab/mmrazor/tree/master/configs/pruning/autoslim#split-checkpoint) should be the same as in step3.

**Comment by tanghy2016** [comment]
Yes, in my experiment, I have gone to step 4, and as you can see from our execution command, it contains 3 YAML file inputs, and these 3 files are the output of step 2

**Comment by pprp** [comment]
Hi, @tanghy2016 . You can try the following commands, which changed the comma to a space.

```
python ./tools/model_converters/split_checkpoint.py \
   configs/pruning/autoslim/autoslim_mbv2_supernet_8xb256_ci10.py \
   output/epoch_49.pth \
   --channel-cfgs output/subnet_497881198.yaml output/subnet_297081551.yaml output/subnet_197465826.yaml
```

**Comment by tanghy2016** [comment]
By the way, why is the accuracy of step 1 relatively low in my two experiments?
The first experiment used the CIFAR10 dataset, scaled to 224, and used mobilenet-v2. After step 1, the accuracy rate was only about 15%.
The second experiment uses the 2-category data set prepared by myself, which is also scaled to 224. Using mobilenet-v2, after step 1, the accuracy rate is only about 50%.
The configuration files of the two experiments refer to [autoslim_mbv2_supernet_8xb256_in1k.py](https://github.com/open-mmlab/mmrazor/blob/master/configs/pruning/autoslim/autoslim_mbv2_supernet_8xb256_in1k.py), and no other changes have been made except to modify the path of the dataset.

**Comment by tanghy2016** [comment]
> 

same error: ```AttributeError: 'AutoSlim' object has no attribute 'channel_cfg'```

**Comment by tanghy2016** [comment]
> Hi, @tanghy2016 . You can try the following commands, which changed the comma to a space.
> 
> ```
> python ./tools/model_converters/split_checkpoint.py \
>    configs/pruning/autoslim/autoslim_mbv2_supernet_8xb256_ci10.py \
>    output/epoch_49.pth \
>    --channel-cfgs output/subnet_497881198.yaml output/subnet_297081551.yaml output/subnet_197465826.yaml
> ```


same error: ```AttributeError: 'AutoSlim' object has no attribute 'channel_cfg'```

**Comment by pprp** [comment]
> 

May you should change `--channel-cfg` to `--channel-cfgs`.

**Comment by tanghy2016** [comment]
I use ```--channel-cfgs``` in my execution command, do you have time to reproduce my experiment? My configuration is as follows:

```python
# copy autoslim_mbv2_supernet_8xb256_in1k.py to autoslim_mbv2_supernet_8xb256_ci10.py
# modify the configuration in autoslim_mbv2_supernet_8xb256_ci10.py as follows:

_base_ = [
    '../../_base_/datasets/mmcls/cifar10_bs16.py',
    '../../_base_/schedules/mmcls/cifar10_bs128.py',
    '../../_base_/mmcls_runtime.py'
]

model = dict(
  # ...
  head=dict(
    # ...
    num_classes=10,
    # ...
  )
  # ...
)

# 将configs/_base_/datasets/mmcls/cifar10_bs16.py中的:
dict(type='RandomCrop', size=32, padding=4),
# 修改为:
dict(type='RandomResizedCrop', size=224),
# 以符合mobilenet v2的输入要求
```

Refer to [issues 138](https://github.com/open-mmlab/mmrazor/issues/138#issuecomment-1097889359)

```python
# add ```optimizer_config = None``` into ```configs/pruning/autoslim/autoslim_mbv2_supernet_8xb256_ci10.py```

_base_ = [
    '../../_base_/datasets/mmcls/cifar10_bs16.py',
    '../../_base_/schedules/mmcls/cifar10_bs128.py',
    '../../_base_/mmcls_runtime.py'
]

+ optimizer_config = None
```

**Comment by wutongshenqiu** [comment]
Hi tanghy2016, do you set `retraining` to True in algorithm config?

```python

algorithm = dict(
	# ...
	retraining=True
	# ...
)

```

**Comment by pprp** [comment]
> By the way, why is the accuracy of step 1 relatively low in my two experiments? The first experiment used the CIFAR10 dataset, scaled to 224, and used mobilenet-v2. After step 1, the accuracy rate was only about 15%. The second experiment uses the 2-category data set prepared by myself, which is also scaled to 224. Using mobilenet-v2, after step 1, the accuracy rate is only about 50%. The configuration files of the two experiments refer to [autoslim_mbv2_supernet_8xb256_in1k.py](https://github.com/open-mmlab/mmrazor/blob/master/configs/pruning/autoslim/autoslim_mbv2_supernet_8xb256_in1k.py), and no other changes have been made except to modify the path of the dataset.

Hi, tanghy2016. [The official codebase](https://github.com/JiahuiYu/slimmable_networks) didn't release the code about training on CIFAR10. We have not attempted to train AutoSlim on the CIFAR10 dataset.

According to the accuracy you reported, we conclude that the supernet failed to converge. Can you find some examples of MobileNetv2 trained on CIFAR10? You can try to modify our supernet to adapt it to CIFAR10 dataset.

**Comment by tanghy2016** [comment]
CIFAR10 is used in the [paper](https://github.com/open-mmlab/mmrazor/tree/master/configs/pruning/autoslim) and results are given

**Comment by pppppM** [comment]
Although the results on CIFAR10 are given in the paper, there are still many things that have not been released, such as the model structure searched on CIFAR10.
Maybe you can follow the 32x32 to continue the next steps to verify the accuracy. 
The result of the first step on imagenet is only 50%~60%, but the final result can reach more than 70%.

**Comment by tanghy2016** [comment]
> Hi tanghy2016, do you set `retraining` to True in algorithm config?
> 
> ```python
> algorithm = dict(
> 	# ...
> 	retraining=True
> 	# ...
> )
> ```

Thank you very much, the problem has been solved

**Comment by tanghy2016** [comment]
> Although the results on CIFAR10 are given in the paper, there are still many things that have not been released, such as the model structure searched on CIFAR10. Maybe you can follow the 32x32 to continue the next steps to verify the accuracy. The result of the first step on imagenet is only 50%~60%, but the final result can reach more than 70%.

The experimental results show that the accuracy rate of subnet is 77%, which is far from the paper. ಥ_ಥ

**Comment by VJeee** [comment]
> > Although the results on CIFAR10 are given in the paper, there are still many things that have not been released, such as the model structure searched on CIFAR10. Maybe you can follow the 32x32 to continue the next steps to verify the accuracy. The result of the first step on imagenet is only 50%~60%, but the final result can reach more than 70%.
> 
> The experimental results show that the accuracy rate of subnet is 77%, which is far from the paper. ಥ_ಥ

Is the size of the weight files obtained by split_checkpoint.py all the same?
