### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by dzyjjpy** [open-mmlab/mmrazor#148]
Got error when run the following command : 
**Step 2: Supernet fine-tuning on COCO**
python ./tools/mmdet/train_mmdet.py \
  configs/nas/detnas/detnas_supernet_frcnn_shufflenetv2_fpn_1x_coco.py \
  --work-dir $WORK_DIR \
  --cfg-options load_from=$STEP1_CKPT

**error:** 
envs/mmrazor/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 210, in _check_default_pg
    assert _default_pg is not None, \
AssertionError: Default process group is not initialized

have trained pre-train model by Step1

Dose anyone have similar mistake?

**Comment by humu789** [comment]
You can ref to #42, maybe it can help you.

**Comment by dzyjjpy** [comment]
> You can ref to #42, maybe it can help you.

thanks for your reply. I will check

**Comment by dzyjjpy** [comment]
As I use single GPU， but used syncbn. replace syncbn to bn can solve the issue :) 
btw, dist_train.sh with multiple GPU has no problem.
