### ISSUE TITLE
[Bug]Doesn't work correctly according to the docs/en/train.md#distill

### ISSUE THREAD

**Issue by JennieDD** [open-mmlab/mmrazor#151]
### Describe the bug
```
python ./tools/mmdet/train_mmdet.py \
  configs/distill/cwd/cwd_cls_head_pspnet_r101_d8_pspnet_r18_d8_512x1024_cityscapes_80k.py \
  --work-dir my_workdir \
  --cfg-options algorithm.distiller.teacher.init_cfg.type=Pretrained algorithm.distiller.teacher.init_cfg.checkpoint=https://download.openmmlab.com/mmsegmentation/v0.5/pspnet/pspnet_r101-d8_512x1024_80k_cityscapes/pspnet_r101-d8_512x1024_80k_cityscapes_20200606_112211-e1e1100f.pth
```
运行docs/en/train.md 的distill的代码时候报错：
AttributeError: GeneralDistill: MMSegArchitecture: 'NoneType' object has no attribute 'parent'
我自己的配置如下图：
![image](https://user-images.githubusercontent.com/104477720/165432138-bd166749-2de2-44f1-9310-6aea7bfad646.png)

**Comment by pprp** [comment]
Hi, JennieDD, thank you for your attention. 

Can you provide the whole log?

**Comment by pprp** [comment]
You can try this command: 

```
python ./tools/mmseg/train_mmseg.py \
  configs/distill/cwd/cwd_cls_head_pspnet_r101_d8_pspnet_r18_d8_512x1024_cityscapes_80k.py \
  --work-dir my_workdir \
  --cfg-options algorithm.distiller.teacher.init_cfg.type=Pretrained algorithm.distiller.teacher.init_cfg.checkpoint=https://download.openmmlab.com/mmsegmentation/v0.5/pspnet/pspnet_r101-d8_512x1024_80k_cityscapes/pspnet_r101-d8_512x1024_80k_cityscapes_20200606_112211-e1e1100f.pth
```

**Comment by JennieDD** [comment]
I have tried your command:
```
python ./tools/mmseg/train_mmseg.py \
  configs/distill/cwd/cwd_cls_head_pspnet_r101_d8_pspnet_r18_d8_512x1024_cityscapes_80k.py \
  --work-dir my_workdir \
  --cfg-options algorithm.distiller.teacher.init_cfg.type=Pretrained algorithm.distiller.teacher.init_cfg.checkpoint=https://download.openmmlab.com/mmsegmentation/v0.5/pspnet/pspnet_r101-d8_512x1024_80k_cityscapes/pspnet_r101-d8_512x1024_80k_cityscapes_20200606_112211-e1e1100f.pth
```
but 
![image](https://user-images.githubusercontent.com/104477720/165435563-62b5d4ba-a058-4268-91c2-55ef77d68ea0.png)

**Comment by pprp** [comment]
Hi, JennieDD, You can change this line:

https://github.com/open-mmlab/mmrazor/blob/e4e95131a2451f748923fe702c269d02c9a753f6/tools/mmseg/train_mmseg.py#L180

to:

```
set_random_seed(seed, deterministic=args.deterministic)
```

**Comment by pppppM** [comment]
@JennieDD  Thanks for your issue.

I'm sorry for the inconvenience caused to you.
We will fix the errors in the documentation and code as soon as possible.

In order not to affect your work, you can temporarily modify it according to the above method.

**Comment by JennieDD** [comment]
@pprp 
修改代码之后成功下载了权重文件之后还是会报错，
```
Traceback (most recent call last):
  File "./tools/mmseg/train_mmseg.py", line 232, in <module>
    main()
  File "./tools/mmseg/train_mmseg.py", line 200, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/opt/conda/lib/python3.8/site-packages/mmseg/datasets/builder.py", line 85, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
FileNotFoundError: CityscapesDataset: [Errno 2] No such file or directory: 'data/cityscapes/leftImg8bit/train'
```

**Comment by pprp** [comment]
Hi, @JennieDD 

Please make sure that you have downloaded the [leftImg8bit_trainvaltest.zip (11GB)](https://www.cityscapes-dataset.com/file-handling/?packageID=3) [[md5]](https://www.cityscapes-dataset.com/md5-sum/?packageID=3) and then refer to the [mmsegmentation document](https://mmsegmentation.readthedocs.io/en/latest/dataset_prepare.html#cityscapes) to convert the dataset.
