### ISSUE TITLE
How to use pickle file created by pruning supernet search

### ISSUE THREAD

**Issue by firatbey** [open-mmlab/mmrazor#158]
### How to use the pickle file from pruning subnet search
I have searched subnet on a trained supernet in the pruning section using the command ([Reference](https://github.com/open-mmlab/mmrazor/tree/master/configs/pruning/autoslim))

```
python ./tools/mmcls/search_mmcls.py \
  configs/pruning/autoslim/autoslim_mbv2_search_8xb1024_in1k.py \
  your_pre-training_checkpoint_path \
  --work-dir your_work_dir
```

The output is `latest.pkl` in my `work_directory`, how can I use this pickle file to create a pruned model?
I would appreciate any pointers, I could not find any step on how to proceed and use this file.

**Comment by humu789** [comment]
`latest.pkl` is used to resume searching, similar to  searcher's ckpt.
The searched subnet is saved in `.YAML` file
