### ISSUE TITLE
How does interfence do in mmrazor?

### ISSUE THREAD

**Issue by Audrey528** [open-mmlab/mmrazor#175]
I wanna  use distilled model based mmdetection to test. And I have read the offical document and checked the code of mmrazor/tests/test_apis/test_inference.py and mmrazor/mmrazor/apis/mmdet/inference.py. I use "init_mmdet_model" to test, it got wrong. MMCV is 1.5.0. The code as follows:

```
from mmdet.apis import init_detector, inference_detector
from mmrazor.apis import init_mmdet_model
config_file = 'cwd_gfl_r101_fpn_gfl_r18_fpn_voc.py'
checkpoint_file = 'epoch_7.pth'
model = init_mmdet_model(config_file, checkpoint_file) #加载模型
img = '20220428.jpg'
result = inference_detector(model, img) #推理图片
model.show_result(img, result, out_file="001.jpg")
```

Question as follows:
![1654574125(1)](https://user-images.githubusercontent.com/68552295/172292594-4fe7eba7-bbc8-48a6-a0d1-4cd7437282e5.png)

**Comment by wutongshenqiu** [comment]
Hi, Audrey528. Thanks for your report!

This might be a bug in `init_mmdet_model`, could you please change [line 44](https://github.com/open-mmlab/mmrazor/blob/master/mmrazor/apis/mmdet/inference.py#L44) as follows and try again

```python
model_cfg.train_cfg = None
```

**Comment by pppppM** [comment]
Pls make a PR to fix it @wutongshenqiu
