### ISSUE TITLE
Step 3 DetNAS stopped at the end of epoch.

### ISSUE THREAD

**Issue by daitranskku** [open-mmlab/mmrazor#183]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

Step 3 DetNAS stopped at the end of epoch.
I have previously trained complete DetNAS steps in MMRazor. I wonder if this error is related to the norm cfg SyncBN update or MMRazor version.
Thank you.

### Post related information

2022-06-20 00:06:26,637 - mmdet - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) [GCC 10.3.0]
CUDA available: True
GPU 0,1: NVIDIA RTX A6000
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.6.r11.6/compiler.30794723_0
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PyTorch: 1.10.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2022.0-Product Build 20211112 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.2
OpenCV: 4.5.5
MMCV: 1.4.8
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.23.0+4f0f5ff
------------------------------------------------------------

2022-06-20 00:06:26,638 - mmdet - INFO - Distributed training: True
2022-06-20 00:06:28,873 - mmdet - INFO - Config:
dataset_type = 'CocoDataset'
data_root = 'data/coco/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(type='LoadAnnotations', with_bbox=True),
    dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
    dict(type='RandomFlip', flip_ratio=0.5),
    dict(
        type='Normalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='Pad', size_divisor=32),
    dict(type='DefaultFormatBundle'),
    dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(1333, 800),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='Collect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=128,
    workers_per_gpu=8,
    train=dict(
        type='CocoDataset',
        ann_file=
        '',
        img_prefix=',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(type='LoadAnnotations', with_bbox=True),
            dict(type='Resize', img_scale=(1333, 800), keep_ratio=True),
            dict(type='RandomFlip', flip_ratio=0.5),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='DefaultFormatBundle'),
            dict(type='Collect', keys=['img', 'gt_bboxes', 'gt_labels'])
        ],
        classes=('09', '10', '11', '12', '13', '16', '17', '18')),
    val=dict(
        type='CocoDataset',
        ann_file=
        '',
        img_prefix='',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('09', '10', '11', '12', '13', '16', '17', '18')),
    test=dict(
        type='CocoDataset',
        ann_file=
        '',
        img_prefix='',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(1333, 800),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='Collect', keys=['img'])
                ])
        ],
        classes=('09', '10', '11', '12', '13', '16', '17', '18'),
        test_mode=True))
evaluation = dict(interval=1, metric='bbox', classwise=True)
optimizer = dict(type='SGD', lr=0.02, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=500,
    warmup_ratio=0.001,
    step=[8, 11])
runner = dict(type='EpochBasedRunner', max_epochs=20)
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
custom_hooks = [dict(type='NumClassCheckHook')]
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = ''
workflow = [('train', 1)]
classes_list = ('09', '10', '11', '12', '13', '16', '17', '18')
class_num = 8
norm_cfg = dict(type='SyncBN', requires_grad=True)
model = dict(
    type='mmdet.FasterRCNN',
    backbone=dict(
        type='mmcls.SearchableShuffleNetV2',
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        out_indices=(0, 1, 2, 3),
        widen_factor=1.0,
        with_last_layer=False),
    neck=dict(
        type='FPN',
        norm_cfg=dict(type='SyncBN', requires_grad=True),
        in_channels=[64, 160, 320, 640],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared4Conv1FCBBoxHead',
            norm_cfg=dict(type='SyncBN', requires_grad=True),
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=8,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0))),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
            nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100)))
mutator = dict(
    type='OneShotMutator',
    placeholder_mapping=dict(
        all_blocks=dict(
            type='OneShotOP',
            choices=dict(
                shuffle_3x3=dict(
                    type='ShuffleBlock',
                    norm_cfg=dict(type='SyncBN', requires_grad=True),
                    kernel_size=3),
                shuffle_5x5=dict(
                    type='ShuffleBlock',
                    norm_cfg=dict(type='SyncBN', requires_grad=True),
                    kernel_size=5),
                shuffle_7x7=dict(
                    type='ShuffleBlock',
                    norm_cfg=dict(type='SyncBN', requires_grad=True),
                    kernel_size=7),
                shuffle_xception=dict(
                    type='ShuffleXception',
                    norm_cfg=dict(type='SyncBN', requires_grad=True))))))
algorithm = dict(
    type='DetNAS',
    architecture=dict(
        type='MMDetArchitecture',
        model=dict(
            type='mmdet.FasterRCNN',
            backbone=dict(
                type='mmcls.SearchableShuffleNetV2',
                norm_cfg=dict(type='SyncBN', requires_grad=True),
                out_indices=(0, 1, 2, 3),
                widen_factor=1.0,
                with_last_layer=False),
            neck=dict(
                type='FPN',
                norm_cfg=dict(type='SyncBN', requires_grad=True),
                in_channels=[64, 160, 320, 640],
                out_channels=256,
                num_outs=5),
            rpn_head=dict(
                type='RPNHead',
                in_channels=256,
                feat_channels=256,
                anchor_generator=dict(
                    type='AnchorGenerator',
                    scales=[8],
                    ratios=[0.5, 1.0, 2.0],
                    strides=[4, 8, 16, 32, 64]),
                bbox_coder=dict(
                    type='DeltaXYWHBBoxCoder',
                    target_means=[0.0, 0.0, 0.0, 0.0],
                    target_stds=[1.0, 1.0, 1.0, 1.0]),
                loss_cls=dict(
                    type='CrossEntropyLoss', use_sigmoid=True,
                    loss_weight=1.0),
                loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
            roi_head=dict(
                type='StandardRoIHead',
                bbox_roi_extractor=dict(
                    type='SingleRoIExtractor',
                    roi_layer=dict(
                        type='RoIAlign', output_size=7, sampling_ratio=0),
                    out_channels=256,
                    featmap_strides=[4, 8, 16, 32]),
                bbox_head=dict(
                    type='Shared4Conv1FCBBoxHead',
                    norm_cfg=dict(type='SyncBN', requires_grad=True),
                    in_channels=256,
                    fc_out_channels=1024,
                    roi_feat_size=7,
                    num_classes=8,
                    bbox_coder=dict(
                        type='DeltaXYWHBBoxCoder',
                        target_means=[0.0, 0.0, 0.0, 0.0],
                        target_stds=[0.1, 0.1, 0.2, 0.2]),
                    reg_class_agnostic=False,
                    loss_cls=dict(
                        type='CrossEntropyLoss',
                        use_sigmoid=False,
                        loss_weight=1.0),
                    loss_bbox=dict(type='L1Loss', loss_weight=1.0))),
            train_cfg=dict(
                rpn=dict(
                    assigner=dict(
                        type='MaxIoUAssigner',
                        pos_iou_thr=0.7,
                        neg_iou_thr=0.3,
                        min_pos_iou=0.3,
                        match_low_quality=True,
                        ignore_iof_thr=-1),
                    sampler=dict(
                        type='RandomSampler',
                        num=256,
                        pos_fraction=0.5,
                        neg_pos_ub=-1,
                        add_gt_as_proposals=False),
                    allowed_border=-1,
                    pos_weight=-1,
                    debug=False),
                rpn_proposal=dict(
                    nms_pre=2000,
                    max_per_img=1000,
                    nms=dict(type='nms', iou_threshold=0.7),
                    min_bbox_size=0),
                rcnn=dict(
                    assigner=dict(
                        type='MaxIoUAssigner',
                        pos_iou_thr=0.5,
                        neg_iou_thr=0.5,
                        min_pos_iou=0.5,
                        match_low_quality=False,
                        ignore_iof_thr=-1),
                    sampler=dict(
                        type='RandomSampler',
                        num=512,
                        pos_fraction=0.25,
                        neg_pos_ub=-1,
                        add_gt_as_proposals=True),
                    pos_weight=-1,
                    debug=False)),
            test_cfg=dict(
                rpn=dict(
                    nms_pre=1000,
                    max_per_img=1000,
                    nms=dict(type='nms', iou_threshold=0.7),
                    min_bbox_size=0),
                rcnn=dict(
                    score_thr=0.05,
                    nms=dict(type='nms', iou_threshold=0.5),
                    max_per_img=100)),
            pretrained=None)),
    mutator=dict(
        type='OneShotMutator',
        placeholder_mapping=dict(
            all_blocks=dict(
                type='OneShotOP',
                choices=dict(
                    shuffle_3x3=dict(
                        type='ShuffleBlock',
                        norm_cfg=dict(type='SyncBN', requires_grad=True),
                        kernel_size=3),
                    shuffle_5x5=dict(
                        type='ShuffleBlock',
                        norm_cfg=dict(type='SyncBN', requires_grad=True),
                        kernel_size=5),
                    shuffle_7x7=dict(
                        type='ShuffleBlock',
                        norm_cfg=dict(type='SyncBN', requires_grad=True),
                        kernel_size=7),
                    shuffle_xception=dict(
                        type='ShuffleXception',
                        norm_cfg=dict(type='SyncBN', requires_grad=True)))))),
    pruner=None,
    distiller=None,
    retraining=False,
    bn_training_mode=True)
find_unused_parameters = True
work_dir = ''
searcher = dict(
    type='EvolutionSearcher',
    metrics='bbox',
    score_key='bbox_mAP',
    constraints=dict(flops=300000000.0),
    candidate_pool_size=50,
    candidate_top_k=10,
    max_epoch=20,
    num_mutation=20,
    num_crossover=20)

2022-06-20 00:06:36,859 - mmdet - INFO - build search...
2022-06-20 00:06:36,859 - mmdet - INFO - start search...
2022-06-20 00:06:36,859 - mmdet - INFO - Experiment setting:
2022-06-20 00:06:36,859 - mmdet - INFO - candidate_pool_size: 50
2022-06-20 00:06:36,859 - mmdet - INFO - candidate_top_k: 10
2022-06-20 00:06:36,859 - mmdet - INFO - num_crossover: 20
2022-06-20 00:06:36,859 - mmdet - INFO - num_mutation: 20
2022-06-20 00:06:36,859 - mmdet - INFO - mutate_prob: 0.1
2022-06-20 00:06:36,860 - mmdet - INFO - max_epoch: 20
2022-06-20 00:06:36,860 - mmdet - INFO - score_key: bbox_mAP
2022-06-20 00:06:36,860 - mmdet - INFO - constraints: {'flops': 300000000.0}
2022-06-20 00:06:36,860 - mmdet - INFO - ####################################################################################################
2022-06-20 00:07:13,926 - mmdet - INFO - Epoch:[1/20] Candidate:[1/50] Score:0.671
2022-06-20 00:07:37,464 - mmdet - INFO - Epoch:[1/20] Candidate:[2/50] Score:0.669
2022-06-20 00:08:01,895 - mmdet - INFO - Epoch:[1/20] Candidate:[3/50] Score:0.663
2022-06-20 00:08:27,541 - mmdet - INFO - Epoch:[1/20] Candidate:[4/50] Score:0.668
2022-06-20 00:08:52,525 - mmdet - INFO - Epoch:[1/20] Candidate:[5/50] Score:0.676
2022-06-20 00:09:16,574 - mmdet - INFO - Epoch:[1/20] Candidate:[6/50] Score:0.675
2022-06-20 00:09:40,488 - mmdet - INFO - Epoch:[1/20] Candidate:[7/50] Score:0.671
2022-06-20 00:10:04,143 - mmdet - INFO - Epoch:[1/20] Candidate:[8/50] Score:0.673
2022-06-20 00:10:27,255 - mmdet - INFO - Epoch:[1/20] Candidate:[9/50] Score:0.657
2022-06-20 00:10:51,471 - mmdet - INFO - Epoch:[1/20] Candidate:[10/50] Score:0.664
2022-06-20 00:11:15,030 - mmdet - INFO - Epoch:[1/20] Candidate:[11/50] Score:0.678
2022-06-20 00:11:37,455 - mmdet - INFO - Epoch:[1/20] Candidate:[12/50] Score:0.67
2022-06-20 00:12:02,248 - mmdet - INFO - Epoch:[1/20] Candidate:[13/50] Score:0.668
2022-06-20 00:12:26,037 - mmdet - INFO - Epoch:[1/20] Candidate:[14/50] Score:0.679
2022-06-20 00:12:49,382 - mmdet - INFO - Epoch:[1/20] Candidate:[15/50] Score:0.673
2022-06-20 00:13:13,355 - mmdet - INFO - Epoch:[1/20] Candidate:[16/50] Score:0.668
2022-06-20 00:13:36,942 - mmdet - INFO - Epoch:[1/20] Candidate:[17/50] Score:0.671
2022-06-20 00:13:59,897 - mmdet - INFO - Epoch:[1/20] Candidate:[18/50] Score:0.67
2022-06-20 00:14:24,696 - mmdet - INFO - Epoch:[1/20] Candidate:[19/50] Score:0.68
2022-06-20 00:14:49,772 - mmdet - INFO - Epoch:[1/20] Candidate:[20/50] Score:0.679
2022-06-20 00:15:14,852 - mmdet - INFO - Epoch:[1/20] Candidate:[21/50] Score:0.669
2022-06-20 00:15:38,650 - mmdet - INFO - Epoch:[1/20] Candidate:[22/50] Score:0.664
2022-06-20 00:16:02,580 - mmdet - INFO - Epoch:[1/20] Candidate:[23/50] Score:0.677
2022-06-20 00:16:26,230 - mmdet - INFO - Epoch:[1/20] Candidate:[24/50] Score:0.67
2022-06-20 00:16:50,930 - mmdet - INFO - Epoch:[1/20] Candidate:[25/50] Score:0.67
2022-06-20 00:17:13,409 - mmdet - INFO - Epoch:[1/20] Candidate:[26/50] Score:0.669
2022-06-20 00:17:37,563 - mmdet - INFO - Epoch:[1/20] Candidate:[27/50] Score:0.673
2022-06-20 00:18:00,440 - mmdet - INFO - Epoch:[1/20] Candidate:[28/50] Score:0.672
2022-06-20 00:18:24,621 - mmdet - INFO - Epoch:[1/20] Candidate:[29/50] Score:0.669
2022-06-20 00:18:49,357 - mmdet - INFO - Epoch:[1/20] Candidate:[30/50] Score:0.672
2022-06-20 00:19:13,222 - mmdet - INFO - Epoch:[1/20] Candidate:[31/50] Score:0.674
2022-06-20 00:19:36,846 - mmdet - INFO - Epoch:[1/20] Candidate:[32/50] Score:0.664
2022-06-20 00:20:01,553 - mmdet - INFO - Epoch:[1/20] Candidate:[33/50] Score:0.665
2022-06-20 00:20:26,531 - mmdet - INFO - Epoch:[1/20] Candidate:[34/50] Score:0.679
2022-06-20 00:20:50,067 - mmdet - INFO - Epoch:[1/20] Candidate:[35/50] Score:0.678
2022-06-20 00:21:13,592 - mmdet - INFO - Epoch:[1/20] Candidate:[36/50] Score:0.669
2022-06-20 00:21:39,057 - mmdet - INFO - Epoch:[1/20] Candidate:[37/50] Score:0.677
2022-06-20 00:22:02,136 - mmdet - INFO - Epoch:[1/20] Candidate:[38/50] Score:0.668
2022-06-20 00:22:25,914 - mmdet - INFO - Epoch:[1/20] Candidate:[39/50] Score:0.679
2022-06-20 00:22:48,816 - mmdet - INFO - Epoch:[1/20] Candidate:[40/50] Score:0.677
2022-06-20 00:23:13,405 - mmdet - INFO - Epoch:[1/20] Candidate:[41/50] Score:0.676
2022-06-20 00:23:36,426 - mmdet - INFO - Epoch:[1/20] Candidate:[42/50] Score:0.678
2022-06-20 00:24:00,631 - mmdet - INFO - Epoch:[1/20] Candidate:[43/50] Score:0.672
2022-06-20 00:24:24,840 - mmdet - INFO - Epoch:[1/20] Candidate:[44/50] Score:0.676
2022-06-20 00:24:47,924 - mmdet - INFO - Epoch:[1/20] Candidate:[45/50] Score:0.674
2022-06-20 00:25:13,855 - mmdet - INFO - Epoch:[1/20] Candidate:[46/50] Score:0.682
2022-06-20 00:25:40,585 - mmdet - INFO - Epoch:[1/20] Candidate:[47/50] Score:0.672
2022-06-20 00:26:05,340 - mmdet - INFO - Epoch:[1/20] Candidate:[48/50] Score:0.661
2022-06-20 00:26:28,722 - mmdet - INFO - Epoch:[1/20] Candidate:[49/50] Score:0.671
2022-06-20 00:26:51,413 - mmdet - INFO - Epoch:[1/20] Candidate:[50/50] Score:0.669
2022-06-20 00:26:51,413 - mmdet - INFO - top k scores before update: []
2022-06-20 00:26:51,414 - mmdet - INFO - top k scores before update: [0.682, 0.68, 0.679, 0.678, 0.677, 0.676, 0.675, 0.674, 0.673, 0.672]
2022-06-20 00:26:51,992 - mmdet - INFO - Epoch:[1/20], top1_score: 0.682

**Comment by humu789** [comment]
`candidate_pool_size` should equal `num_mutation` + `num_crossover`, otherwise `candidate_pool_size`s of rank 0 and rank 1 are different. It will cause waiting when `broadcast_object_list` is called.
