### ISSUE TITLE
mmcv-full version in Requirements.txt maybe wrong

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmrazor#20]
My mmcv-full==1.3.8, but I can't run this repo for the following code line in `detnas.py`:
https://github.com/open-mmlab/mmrazor/blob/532b59b9ca71f17c8728081f85fa666d5884a823/mmrazor/models/algorithms/detnas.py#L5
Please modify the mmcv-full version in requirements.txt to `mmcv-full=1.3.13`.
![image](https://user-images.githubusercontent.com/23122139/147340029-37a6ab5f-1bd2-4edc-bf99-e4c927ba3501.png)

**Comment by pppppM** [comment]
Thanks for your issue.
We will fix the bug quickly.
Please @HIT-cwh update `requirements.txt`

**Comment by Senwang98** [comment]
@pppppM 
Thanks for your reply.
@HIT-cwh 
Sorry for disturb, could you update the mmcv-full version to 1.3.13 in requirements folder?
