### ISSUE TITLE
Will mmrazor add more pruners ?[Feature]

### ISSUE THREAD

**Issue by XYAskWhy** [open-mmlab/mmrazor#203]
### Motivation
Autoslim is more a nas-like algothrim than a conventional and easy-to-use prune method, and it is pretty out of date in terms of performance. Any plan on adding some new pruners? Such as norm pruner, slimming pruner, Taylor pruner and Lottery Ticket pruner, etc.

**Comment by LKJacky** [comment]
Yes, we will release more pruning algorithms, like L1-norm, APoz, FPGM, etc. They will come soon. Please keep following our repository.
You can let us know if you have any algorithms you specifically want, and we may prioritize them.

**Comment by XYAskWhy** [comment]
Thanks for your timely reply. Either comes out first is OK, and it'd be great to have a user guide on how to apply these pruners to downstream tasks,  such as detection and segmentation.

**Comment by LKJacky** [comment]
Yes, we are also preparing user guides for downstream tasks. The new version of mmrazor will have more and better documents and user guides. Stay tuned!
