### ISSUE TITLE
[Feature] Support a SOTA channel pruning method, ResRep.

### ISSUE THREAD

**Issue by DingXiaoH** [open-mmlab/mmrazor#21]
### Describe the feature

A SOTA channel pruning method, ResRep.

### Motivation

This method is the SOTA static channel pruning method. It prunes a standard Res50 with over 50% FLOPs reduction and zero accuracy drop. 

MMRazor is an awesome framework, but I am too busy these days so I would really appreciate it you could implement it in MMRazor. 

### Related resources

https://openaccess.thecvf.com/content/ICCV2021/html/Ding_ResRep_Lossless_CNN_Pruning_via_Decoupling_Remembering_and_Forgetting_ICCV_2021_paper.html

https://github.com/DingXiaoH/ResRep

**Comment by pppppM** [comment]
Thanks for your attention to MMRazor. 

I'm very excited to receive your issue！
My colleagues and I agree that ResRep is excellent work, and we will start to reproduce ResRep as soon as possible.  
Could we invite you to review at that time? @DingXiaoH
