### ISSUE TITLE
mmRazor workflow

### ISSUE THREAD

**Issue by rick-van-veen** [open-mmlab/mmrazor#234]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I currently have a number of pre-trained mmdetection architectures (maskrcnn, yolact, solo) re-trained on my own custom segmentation task. They work well, but I am interested in reducing these models as much as possible and am interested in using a knowledge distillation technique. 

Can I achieve this using mmrazor? If yes, how do I do that? What is the workflow? 

Some specific questions:
1. Do I need to retrain a teacher model using mmrazor or can I use my already trained models trained using the mmdetection?
2. Do I need to extend the KD algorithms such that I can use them for my specific task and chosen architectures or does it just support any mmdetection architecture and any segmentation task in general?

### Post related information

n/a

**Comment by HIT-cwh** [comment]
Hi! Please refer [CWD](https://github.com/open-mmlab/mmrazor/tree/dev-1.x/configs/distill/mmdet/cwd) and [PKD](https://github.com/open-mmlab/mmrazor/pull/304). If you have any questions, please let us know.
