### ISSUE TITLE
Where can I change the Supernet search blocks in DetNAS to 40 in the original paper?

### ISSUE THREAD

**Issue by JiuTMniJiaoXiaLuo** [open-mmlab/mmrazor#283]
### Describe the question you meet
Where can I change the Supernet search blocks in DetNAS to 40 in the original paper?I have searched for many config files, but I can't find them.
\[here\]

**Comment by humu789** [comment]
searchable architecture is pre-defined, you can implement a new searchable backbone or modify it by referring as follows
https://github.com/open-mmlab/mmrazor/blob/8b57a07b5e6033dbd0052aeaf0f72668bdaecd00/mmrazor/models/architectures/components/backbones/searchable_shufflenet_v2.py#L50

**Comment by JiuTMniJiaoXiaLuo** [comment]
> 可搜索架构是预定义的，您可以实现一个新的可搜索主干或修改它，参考如下
> 
> https://github.com/open-mmlab/mmrazor/blob/8b57a07b5e6033dbd0052aeaf0f72668bdaecd00/mmrazor/models/architectures/components/backbones/searchable_shufflenet_v2.py#L50

Thank you！！！！
