### ISSUE TITLE
Is mmrszor based on MMdetection?

### ISSUE THREAD

**Issue by aiboys** [open-mmlab/mmrazor#33]
Hi, is this codebase based on MMdetection or anyelse?  In other words, does this code base support distillation of detectors (e.g. detection column)?

**Comment by HIT-cwh** [comment]
Reference to [cwd_cls_head_gfl_r101_fpn_gfl_r50_fpn_1x_coco.py](https://github.com/open-mmlab/mmrazor/blob/master/configs/distill/cwd/cwd_cls_head_gfl_r101_fpn_gfl_r50_fpn_1x_coco.py)
