### ISSUE TITLE
custom tracer

### ISSUE THREAD

**Issue by wm901115nwpu** [open-mmlab/mmrazor#351]
model = torch.hub.load('facebookresearch/detr:main', 'detr_resnet50', pretrained=True)
graph = custom_symbolic_trace(model)

/usr/bin/python3 /Users/unicorn/MyCodes/net_op/fx/mmrazor_tracer.py
Using cache found in /Users/unicorn/.cache/torch/hub/facebookresearch_detr_main
/Users/unicorn/Library/Python/3.9/lib/python/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/Users/unicorn/Library/Python/3.9/lib/python/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Downloading: "https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth" to /Users/unicorn/.cache/torch/hub/checkpoints/detr-r50-e632da11.pth
100%|██████████| 159M/159M [00:15<00:00, 10.5MB/s]
Traceback (most recent call last):
  File "/Users/unicorn/MyCodes/net_op/fx/mmrazor_tracer.py", line 284, in <module>
    graph = custom_symbolic_trace(model)
  File "/Users/unicorn/MyCodes/net_op/fx/mmrazor_tracer.py", line 75, in custom_symbolic_trace
    graph = tracer.trace(root, concrete_args)
  File "/Users/unicorn/MyCodes/net_op/fx/mmrazor_tracer.py", line 264, in trace
    'output', (self.create_arg(fn(*args)), ), {},
  File "/Users/unicorn/.cache/torch/hub/facebookresearch_detr_main/models/detr.py", line 61, in forward
    features, pos = self.backbone(samples)
  File "/Users/unicorn/MyCodes/net_op/fx/mmrazor_tracer.py", line 225, in module_getattr_wrapper
    return self._module_getattr(attr, attr_val, parameter_proxy_cache)
AttributeError: 'CustomTracer' object has no attribute '_module_getattr'

**Comment by LKJacky** [comment]
I'm sorry, there is no enough information for me to debug. Please tell us, which branch you are using, and the content of /fx/mmrazor_tracer.py.

**Comment by wm901115nwpu** [comment]
@LKJacky I use quantize branch, mmrazor/models/task_modules/tracer/fx/custom_tracer.py,  I use function of custom_symbolic_trace to trace detr, I find that I can't trace.

**Comment by LKJacky** [comment]
We guess it's because we use a different version of PyTorch. Please try to use torch 1.12.

**Comment by LKJacky** [comment]
Please be cautious, quantize branch is in development, so we cannot guarantee it gets the right result. We will refine it as soon as possible.

**Comment by wm901115nwpu** [comment]
ok, I use pytorch version is 1.13, I think pytorch version may not affect it.

**Comment by LKJacky** [comment]
I have tested with torch1.13 and torch1.12. torch1.12 can trace successfully, and torch1.13 reports the same error as you.
This is because we develop this branch with torch1.12 and we custom fx tracer. But the torch fx tracer changes in torch1.13.

**Comment by wm901115nwpu** [comment]
ok, I try it with torch1.12.

**Comment by wm901115nwpu** [comment]
I fix pytorch 1.13,but positional_encoder occur error,
File "/Users/unicorn/.cache/torch/hub/facebookresearch_detr_main/models/position_encoding.py", line 40, in forward
    dim_t = torch.arange(self.num_pos_feats, dtype=torch.float32, device=x.device)
TypeError: arange() received an invalid combination of arguments - got (int, device=Attribute, dtype=torch.dtype), but expected one of:
 * (Number end, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, *, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (Number start, Number end, Number step, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)

**Comment by LKJacky** [comment]
This branch is leased for quantization design RFC. It is incomplete and unstable. Please wait for us to refine it.

**Comment by wm901115nwpu** [comment]
ok
