### ISSUE TITLE
how to prune one semantic segmentation model?

### ISSUE THREAD

**Issue by worker-ljw** [open-mmlab/mmrazor#354]
i want to prune one semantic segmentation model in mmrazor, but i don't know how to do it.

**Comment by spynccat** [comment]
Please refer to branch dev-1.x: configs/pruning/mmseg/dcff, we provide a segmentation case here.
Ensure you have cloned support libraries and checkout to corresponding branch:
```latex
mmcv-full        2.x
mmrazor          dev-1.x
mmseg            dev-1.x
```

**Comment by spynccat** [comment]
This issue is temporarily closed. Please reopen it if any problem exists.
