### ISSUE TITLE
in distill, how print teacher model accuracy of data

### ISSUE THREAD

**Issue by Manningchan** [open-mmlab/mmrazor#360]

**Comment by wilxy** [comment]
Thanks for your issue.
You can set the `type` of `val_cfg` to `mmrazor.SingleTeacherDistillValLoop` like this [config](https://github.com/open-mmlab/mmrazor/blob/dev-1.x/configs/distill/mmcls/kd/kd_logits_resnet34_resnet18_8xb32_in1k.py#L39).
Then you can get the accuracy of the teacher model during training like this [log](https://download.openmmlab.com/mmrazor/v1/kd/kl_r18_w3/kd_logits_resnet34_resnet18_8xb32_in1k_w3_20221011_181115-5c6a834d.json?versionId=CAEQThiBgMDx_se0oBgiIDQxNTM2MWZjZGRhNjRhZDZiZTIzY2Y0NDU3NDA4ODBl):
```
{"student.accuracy/top1": 29.884000778198242, "student.accuracy/top5": 55.50400161743164, "step": 1}
{"teacher.accuracy/top1": 73.62600708007812, "teacher.accuracy/top5": 91.59000396728516, "step": 1}
```

**Comment by Manningchan** [comment]
> Thanks for your issue. You can set the `type` of `val_cfg` to `mmrazor.SingleTeacherDistillValLoop` like this [config](https://github.com/open-mmlab/mmrazor/blob/dev-1.x/configs/distill/mmcls/kd/kd_logits_resnet34_resnet18_8xb32_in1k.py#L39). Then you can get the accuracy of the teacher model during training like this [log](https://download.openmmlab.com/mmrazor/v1/kd/kl_r18_w3/kd_logits_resnet34_resnet18_8xb32_in1k_w3_20221011_181115-5c6a834d.json?versionId=CAEQThiBgMDx_se0oBgiIDQxNTM2MWZjZGRhNjRhZDZiZTIzY2Y0NDU3NDA4ODBl):
> 
> ```
> {"student.accuracy/top1": 29.884000778198242, "student.accuracy/top5": 55.50400161743164, "step": 1}
> {"teacher.accuracy/top1": 73.62600708007812, "teacher.accuracy/top5": 91.59000396728516, "step": 1}
> ```

thanks for your reply, but i used mmseg，if i add val_cfg，i still can not get the teacher accuracy，and if i add student_recorders and teacher_recorders, it will occurs TypeError: GeneralDistill: SingleTeacherDistiller: __init__() got an unexpected keyword argument 'student_recorders'. i can not find ‘ConfigurableDistiller‘，

**Comment by wilxy** [comment]
Please provide your training `config` and the output of `pip list | grep "mmcv\|mmrazor\|^torch"`.

**Comment by wilxy** [comment]
Your `MMRazor` version is `0.3.1`, which does not support the `recorder` mechanism and `SingleTeacherDistillValLoop`.
Please update the version to `1.0.0rc1` by using the `dev-1.x` branch.

**Comment by wilxy** [comment]
Please reopen it if there are any problems in the future.
