### ISSUE TITLE
Reproduced results of CWD

### ISSUE THREAD

**Issue by Debrove** [open-mmlab/mmrazor#392]
### Checklist

- I have searched related issues but cannot get the expected help.
- I have read related documents and don't know what to do.

### Describe the question you meet

I run the CWD with command
`CUDA_VISIBLE_DEVICES=0 python ./tools/train.py   configs/distill/mmseg/cwd/cwd_logits_pspnet_r101-d8_pspnet_r18-d8_4xb2-80k_cityscapes-512x1024.py --work-dir logs/cwd`

and get the inferior result of student, which is 69.89 mIoU. It seems no improvement from distillation.

Please help me. Thank you.

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
mmcv                    2.0.0rc3
mmcv-full               1.5.0
mmrazor                 1.0.0rc1 
torch                   1.12.1+cu116
torchvision             0.13.1+cu116
2. Your config file if you modified it or created a new one.

No modified config file

3. Your train log file if you meet the problem during training.
Here is my training log file, [20221208_223401.log](https://github.com/open-mmlab/mmrazor/files/10192228/20221208_223401.log)
4. Other code you modified in the `mmrazor` folder.
 No modified

**Comment by wilxy** [comment]
Thanks for your issus, but I cannot open your log file [20221208_223401.log](https://github.com/open-mmlab/mmrazor/files/10192228/20221208_223401.log).
At the same time, the results in cwd's [Readme](https://github.com/open-mmlab/mmrazor/blob/dev-1.x/configs/distill/mmseg/cwd/README.md) are obtained by training with 4 GPUs. It is normal that the distillation result of 1 GPU is not as good as that of 4 GPUs.

![image](https://user-images.githubusercontent.com/43191879/206972400-691db13f-4247-43c3-a650-3b3d421971ef.png)

**Comment by Debrove** [comment]
Thanks for your reply. I solved this problem after I change the batch size to 16 with a single GPU.
