### ISSUE TITLE
Is there an example of mmpose  mmrazor

### ISSUE THREAD

**Issue by APeiZou** [open-mmlab/mmrazor#399]
@lindahua @Johnson-Wang  Hello，Is there an example of mmpose  mmrazor？

**Comment by APeiZou** [comment]
@openmmlab-bot

**Comment by sunnyxiaohu** [comment]
Hi, 
Note that the differences of adapting MMrazor's algorithms to different downstream tasks is almost the same. Bellow gives some examples and may them could help you.
If you are interested in Purning, you can refer to: https://github.com/open-mmlab/mmrazor/tree/dev-1.x/configs/pruning/mmpose/dcff
If you are interested in KD, you can refer to: https://github.com/open-mmlab/mmrazor/tree/dev-1.x/configs/distill
If you are interested in NAS, you can refer to: https://github.com/open-mmlab/mmrazor/blob/dev-1.x/docs/en/advanced_guides/apply_existing_algorithms_to_new_tasks.md

**Comment by APeiZou** [comment]
@sunnyxiaohu   Thanks for your reply.
