### ISSUE TITLE
How to generate fix_subnet config yaml in Darts supernet training?

### ISSUE THREAD

**Issue by dismilk** [open-mmlab/mmrazor#429]
Branch: dev-1.x

Function: NAS-Darts

Train step:
1. train supernet with darts_supernet_unroll_1xb96_cifar10.py
2. train subnet with darts_subnet_1xb96_cifar10_2.0.py

Question:
I finished supernet training and when I want to train subnet, I cannot find fix_subnet config in darts_subnet_1xb96_cifar10_2.0.py. I search '*.yaml'(to find SUBNET_xxx.yaml) in work_dir of supernet train, but only find checkpoint of supernet. The userguide didn't mention it. 
Please tell me how to generate fix_subnet yaml(such as DARTS_SUBNET_CIFAR_PAPER_ALIAS.yaml) in supernet training, thanks!

<img width="846" alt="image" src="https://user-images.githubusercontent.com/31956852/211142421-34b8d207-32f4-4195-a999-e1bafead4cbe.png">

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/31956852/211142397-29832be1-71b2-462d-b596-60aa804d127a.png">

**Comment by gaoyang07** [comment]
Thanks for your reminder.

You can use the `DumpSubnetHook` by adding `custom_hooks = [dict(type='mmrazor.DumpSubnetHook', interval=10, by_epoch=True)]` into the `darts_supernet_unroll_1xb96_cifar10.py` to generate the subnet yaml during supernet training.

We will fix the omit very soon.

**Comment by gaoyang07** [comment]
Fixed in https://github.com/open-mmlab/mmrazor/pull/426/commits/e20da2f2e21e63d6f2be32ff4d8a1d010da53702#diff-a75303b1ea8b545079e1f94fdd2a8f13698a1573c89a3dc1987bce0a71fb0e5dR7
