### ISSUE TITLE
how to only export prunning subnet structure from masked checkpoint and get its flops and param, such as l1-norm prunning algorthm??

### ISSUE THREAD

**Issue by LIULONGEE** [open-mmlab/mmrazor#476]

**Comment by LKJacky** [comment]
@LIULONGEE ，We add the deploy guide for l1-norm in the [pr](https://github.com/open-mmlab/mmrazor/pull/477). Please refer to it, and we will merge it as soon as possible.

**Comment by LIULONGEE** [comment]
great! thanks
