### ISSUE TITLE
[Bug] Some training steps in the README of detnas seem not right

### ISSUE THREAD

**Issue by hunto** [open-mmlab/mmrazor#48]
In the `Getting Started` section of https://github.com/open-mmlab/mmrazor/blob/master/configs/nas/detnas/README.md , the `Step 1` and `Step 4` use `train_mmdet.py` to train the ImageNet-pretrained models, and directly following the commands would occur errors.

I think the training scripts of these two steps might be `train_mmcls.py`, please fix the docs, thanks.

<img width="729" alt="41248f94-6b57-4775-a2a1-434fd24d9c8b" src="https://user-images.githubusercontent.com/23501718/149117263-26b42b12-3af8-4284-afdb-265b9314065d.png">

**Comment by humu789** [comment]
I will fix it as soon, thanks.
