### ISSUE TITLE
when pruning algorithm in rtmdet model, the python file reported errors.

### ISSUE THREAD

**Issue by SicongLiu998** [open-mmlab/mmrazor#486]
### Describe the bug

When I tried to apply pruning algorithm in rtmdet model of mmdet3.0 version, there was an error. And I have followed the steps that had been explained in https://www.bilibili.com/video/BV1wG411u7SP/?spm_id_from=333.337.search-card.all.click&vd_source=22554fd9376254e58d8d9a0505987f7b (33min 56sec). 

\[here\]

### To Reproduce
 
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/65213342/226243293-b17ebba7-bad1-48e7-84dc-d85d3069cfc8.png">
This command could get a right result.
<img width="1458" alt="image" src="https://user-images.githubusercontent.com/65213342/226243454-9a088ede-c37a-4d70-8e6a-2264f9e95435.png">
but in the command reported an error as follow
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/65213342/226243561-b7b85257-a703-4e71-ba01-db848218dfca.png">

and

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/65213342/226243666-b5c73c96-87e4-4aa8-8414-cd91271d3e5c.png">

```shell
[here]
```

### Post related information

1. The output of `pip list | grep "mmcv\|mmrazor\|^torch"`
   \[here\]
2. Your config file if you modified it or created a new one.

```python
[here]
```

3. Your train log file if you meet the problem during training.
   \[here\]
4. Other code you modified in the `mmrazor` folder.
   \[here\]

### Additional context

\[here\]

**Comment by LKJacky** [comment]
This branch is not supported now. We recommend you to use [GroupFisher Algorithm](https://github.com/open-mmlab/mmrazor/tree/dev-1.x/configs/pruning/base/group_fisher), which includes mmdet pruning.

**Comment by LKJacky** [comment]
We closed the issue as there has been no response in a long time. You can reopen it when you need.
