### ISSUE TITLE
Error in visualization of CWD test results.

### ISSUE THREAD

**Issue by sunshiding** [open-mmlab/mmrazor#52]
I get an error when I execute the following command:

python tools/mmseg/test_mmseg.py /home/sunshiding/mmrazor/work_dirs/cwd_cls_head_pspnet_r50_d8_pspnet_r18_d8_512x512_voc12/cwd_cls_head_pspnet_r50_d8_pspnet_r18_d8_512x512_voc12.py /home/sunshiding/mmrazor/work_dirs/cwd_cls_head_pspnet_r50_d8_pspnet_r18_d8_512x512_voc12/iter_4000.pth  --show-dir ./results/cwd_cls_head_pspnet_r50_d8_pspnet_r18_d8_512x512_voc12

The error is as follows：

load checkpoint from local path: /home/sunshiding/mmrazor/work_dirs/cwd_cls_head_pspnet_r50_d8_pspnet_r18_d8_512x512_voc12/iter_4000.pth
[                                                  ] 0/115, elapsed: 0s, ETA:Traceback (most recent call last):
  File "tools/mmseg/test_mmseg.py", line 248, in <module>
    main()
  File "tools/mmseg/test_mmseg.py", line 210, in main
    format_args=eval_kwargs)
  File "/home/sunshiding/mmsegmentation-master/mmseg/apis/test.py", line 140, in single_gpu_test
    opacity=opacity)
  File "/home/sunshiding/.conda/envs/razor/lib/python3.7/site-packages/mmrazor/models/algorithms/base.py", line 170, in show_result
    return self.architecture.show_result(img, result, **kwargs)
  File "/home/sunshiding/.conda/envs/razor/lib/python3.7/site-packages/mmrazor/models/architectures/base.py", line 41, in show_result
    return self.model.show_result(img, result, **kwargs)
  File "/home/sunshiding/mmsegmentation-master/mmseg/models/segmentors/base.py", line 242, in show_result
    assert palette.shape[0] == len(self.CLASSES)
  File "/home/sunshiding/.conda/envs/razor/lib/python3.7/site-packages/torch/nn/modules/module.py", line 779, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'EncoderDecoder' object has no attribute 'CLASSES'

**Comment by wwjwy** [comment]
you can change File "/home/sunshiding/mmsegmentation-master/mmseg/models/segmentors/base.py", line 242, in show_result
assert palette.shape[0] == len(self.CLASSES) to assert palette.shape[0] == 21(the number of classes), i meet the same problem and solve it like this.

**Comment by wutongshenqiu** [comment]
Thanks for your issue. This is probably due to the fact that the `CLASSES` property is only [assigned to `algorithm`](https://github.com/open-mmlab/mmrazor/blob/master/tools/mmseg/test_mmseg.py#L154) instead of the model used in [mmsegmentation](https://github.com/open-mmlab/mmsegmentation/blob/master/tools/test.py#L166), we will fix this soon.

**Comment by wutongshenqiu** [comment]
Could you please modify `test_mmseg.py` according to this pr [open-mmlab/mmrazor#53](https://github.com/open-mmlab/mmrazor/pull/53/files#diff-0847052fd2a0f97c309b372c035b8a3763527b20ff84dc7754f5fdbdab5cadd6R161) and see if there is still an error?

**Comment by sunshiding** [comment]
> Could you please modify `test_mmseg.py` according to this pr [open-mmlab/mmrazor#53](https://github.com/open-mmlab/mmrazor/pull/53/files#diff-0847052fd2a0f97c309b372c035b8a3763527b20ff84dc7754f5fdbdab5cadd6R161) and see if there is still an error?

Thank you very much, this problem has been solved perfectly.
