### ISSUE TITLE
[Bug] Link in the tutorial https://mmrazor.readthedocs.io/en/main/advanced_guides/customize_nas_algorithms.html is wrong.

### ISSUE THREAD

**Issue by Bovey0809** [open-mmlab/mmrazor#558]
### Describe the bug

While reading the tutorial, "mutator" link can't be open for it's form Lark.

### To Reproduce

Clik the link above, ctrl+f "mutator", find the link.

**Comment by humu789** [comment]
https://github.com/open-mmlab/mmrazor/pull/559 Fixed，thanks
