### ISSUE TITLE
Can mmrazor prune the model of mmagic?

### ISSUE THREAD

**Issue by zhongqiu1245** [open-mmlab/mmrazor#560]
Hello!
Thank you for your amazing job!
Can mmrazor prune the model of mmagic?
And can mmrazor prune the pytorch model which not belong to mmopenlab?
Thank you!

**Comment by zhongqiu1245** [comment]
any news？

**Comment by LKJacky** [comment]
Sorry for the late reply.
1. MMRazor provides tools to prune any torch model, so it can prune torch models that do not belong to openmmlab.
2. However, we only test our tools and provide the full pipeline for limited models. If you want to prune your model, please refer to our [docs](https://github.com/open-mmlab/mmrazor/blob/main/docs/en/user_guides/pruning_user_guide.md) and source code.

**Comment by zhongqiu1245** [comment]
Thank you！
