### ISSUE TITLE
[Bug]mmcls needs mmcv-full, while mmrazor now need mmcv>=2.0.0

### ISSUE THREAD

**Issue by CaMi1le** [open-mmlab/mmrazor#602]
### Installing

I have just installed mmrazor as the doc says, including mmcv==2.1.0. I also use pip to install your given requirements.txt.

I want to try the QAT quantization method, so I try your given config, which is in configs/quantization/qat/base/qat_openvino_resnet18_10e_8xb32_in1k.py

It tells me to install mmcls, which is reasonable
![image](https://github.com/open-mmlab/mmrazor/assets/55053441/a3e7faee-fd3c-4e32-801d-818cd612cd8c)
but it comes trouble when installing mmcls, since mmcls supports mmcv-full<1.9.0,>=1.4.2; while mmrazor 1.0.0 now comes to mmcv>=2.0.0. we can use pip install mmcls successfully (mmcls-0.25.0), but when running the QAT it still has problem
![image](https://github.com/open-mmlab/mmrazor/assets/55053441/f059ef38-78a8-4c2b-bef4-468e689dafd8)

Any ideas to solve it? maybe a lower version of mmrazor will help, or mmrazor will support earlier mmcv in the future?

**Comment by henryJhonOt** [comment]
FYI, here's my environment,, and it works out for me

- python=3.8.18
- mmcls=1.0.0rc6
- mmcv=2.0.0
- mmdet=3.1.0
- mmengine=0.8.5
- mmrazor=1.0.0rc2

**Comment by henryJhonOt** [comment]
it seems that 'mmcv-full' was renamed to 'mmcv' in 2.x version

**Comment by CaMi1le** [comment]
> FYI, here's my environment,, and it works out for me
> 
> * python=3.8.18
> * mmcls=1.0.0rc6
> * mmcv=2.0.0
> * mmdet=3.1.0
> * mmengine=0.8.5
> * mmrazor=1.0.0rc2

Thanks for reply. So you donot need to change mmcls into mmpretrain? I found mmcls has been concluded into mmpretrain and it works for my local mmrazor. 

Another incoming question is the use for mmdeploy on QAT model. The tutorial in mmrazor says using mmdeploy, while mmdeploy says using a special branch calls "for_mmrazor", which is too old to be used. I am still struggling with the torch-to-onnx part. Do you have any experience? Thx! 


10/25: The old branch can work fine too, since the _deploy_cfg_ I should use the mmdeploy version, and If you change the train _model_cfg_ in QAT training, the mmdeploy in “for_mmrazzor” will force you change back to mmcls

**Comment by CaMi1le** [comment]
> it seems that 'mmcv-full' was renamed to 'mmcv' in 2.x version

I am still doing experiments on the mmcv part. It is more appropriate to run the latest mmcv correctly before working on the older part of the project, which will be a great task.

The old project is based on mmcv-full==1.7.0 and mmdet==2.27.0, and how to migrate the old mmdet to a new one is still a mist since the tutorial hasn't been working on it.

**Comment by ForrestPi** [comment]
mmrazor should use mmpretrain instead of mmcls

**Comment by CaMi1le** [comment]
> mmrazor should use mmpretrain instead of mmcls

Yes that's my original try, which will face some error in the mmdelpoy things.
The installation of  mmcls=1.0.0rc6 is a real help, which solves my issue.
