### ISSUE TITLE
[Feature] teacher and student model's different data transforms for Distillations

### ISSUE THREAD

**Issue by aiboys** [open-mmlab/mmrazor#67]
### Describe the feature

Since there are some popular distillation algorithms using different data inputs for teacher and student model ,  is there any chance to add such 'Multi-view/Multimodal' input formates features in the future?

**Comment by pppppM** [comment]
Can you provide some specific algorithms?

**Comment by aiboys** [comment]
such as [CRD](https://openreview.net/pdf?id=SkgpBJrtvS), which considered transferring knowledge from
one modality (e.g., RGB) to another (e.g., depth),

**Comment by pppppM** [comment]
This feature is expected to be supported by the end of June
