### ISSUE TITLE
[Feature] More details in README

### ISSUE THREAD

**Issue by flywheel1412** [open-mmlab/mmrazor#68]
### Describe the feature

Could you provied more details (method name, reference etc.) about the algorithms at pruning, KD and NAS ?

**Comment by pppppM** [comment]
Can you describe in detail the information you need?
We have provided some info in the algorithm's readme, such as https://github.com/open-mmlab/mmrazor/tree/master/configs/distill/cwd#readme

**Comment by flywheel1412** [comment]
thx, that is I need.
