### ISSUE TITLE
[Bug] backward after optimzer.step()?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmrazor#69]
I am trying to train autoslim on cifar10 with mobilenetV2.

But I found there are some errors when training

![image](https://user-images.githubusercontent.com/1567200/152935581-6016246c-61b2-4cf0-beaa-1c39b9f4a2cc.png)

And I found some of root cause. For example,

You have already called `optimized.step()` here (https://github.com/open-mmlab/mmrazor/blob/master/mmrazor/models/algorithms/autoslim.py#L226)

but in mmcv here is already have one (https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/hooks/optimizer.py#L56).

Do i need to configure something?

thank you

**Comment by jiehuang165** [comment]
I ran into this issue just now. And I solve it by setting `optimizer_config = None` as https://github.com/open-mmlab/mmrazor/blob/0dd407abc4a3ce251f3f63377384be7eb13ab713/configs/_base_/schedules/mmcls/imagenet_bs2048_autoslim.py#L12
The setting avoids the second call of `backward()` via no registering OptimizerHook.

**Comment by twmht** [comment]
Why not just comment out all the `.backward` and `.step` in  https://github.com/open-mmlab/mmrazor/blob/master/mmrazor/models/algorithms/autoslim.py#L226

I tried and it works.

**Comment by HIT-cwh** [comment]
> Forcing optimize_config to None may not be a good idea, for example, it's not easy to adapt to fp16 training when setting optimizer_config to None.
> 
> Why not just comment out all the `.backward` and `.step` in https://github.com/open-mmlab/mmrazor/blob/master/mmrazor/models/algorithms/autoslim.py#L226
> 
> I tried and it works.

Thank you for your issue.
It does work to comment out all the ``.backward`` and ``.step``. And we use these here just to save GPU memory. It is hacky as it's not easy to adapt to fp16 training. But just using ``OptimizerHook`` may lead to ``cuda out of memory`` when training on bigger dataset, such as Imagenet. We are still working on it.

**Comment by twmht** [comment]
@HIT-cwh 

I am wondering why the current implementation would result OOM, I reimplement with SlimConv2D from https://github.com/JiahuiYu/slimmable_networks/blob/master/models/slimmable_ops.py#L25.

And there is no OOM occur.

**Comment by pppppM** [comment]
@HIT-cwh

**Comment by pppppM** [comment]
> 
> I am wondering why the current implementation would result OOM, I reimplement with SlimConv2D from https://github.com/JiahuiYu/slimmable_networks/blob/master/models/slimmable_ops.py#L25.
> 
> And there is no OOM occur.

It is better to make a new issue to discuss this question. @twmht

**Comment by HIT-cwh** [comment]
> @HIT-cwh
> 
> I am wondering why the current implementation would result OOM, I reimplement with SlimConv2D from https://github.com/JiahuiYu/slimmable_networks/blob/master/models/slimmable_ops.py#L25.
> 
> And there is no OOM occur.

Look [here](https://github.com/JiahuiYu/slimmable_networks/blob/5dc14d0357ccfc596d706281acdc8a5b0b66c6d6/train.py#L476-L497). In the official code, the gradient of the loss is computed immediately for each ``width_mult``. That is, ``loss.backward()`` is executed immediately after ``forward_loss``. So there is no OOM occur.

**Comment by twmht** [comment]
@HIT-cwh 

But you can also do the same thing in mmrazor, where is the OOM from if you do the same thing?

**Comment by HIT-cwh** [comment]
Maybe I didn't make it clear.
code 1:
```
loss1 = forward_loss()
loss2 = forward_loss()
loss3 = forward_loss()
loss = loss1 + loss2 + loss3
loss.backward()
optimizor.step()
```
code2:
```
loss1 = forward_loss()
loss1.backward()
loss2 = forward_loss()
loss2.backward()
loss3 = forward_loss()
loss3.backward()
optimizor.step()
```
The memory cost of code1 is 3 times as much as that of code2

**Comment by twmht** [comment]
Interesting. To the best of my knowledge, I though both use the same memory. Thank you for pointing out that.

**Comment by HIT-cwh** [comment]
> Interesting. To the best of my knowledge, I though both use the same memory. Thank you for pointing out that.

I'm sorry to bother you again. To some degree, the above code2 has the same effect as [grad-cumulating](https://github.com/open-mmlab/mmcv/pull/1221). So, I think the implementation like code2 may save much memory. If it turns out that I'm wrong, please let me know. Thanks.

**Comment by twmht** [comment]
Yup. I think you are right, since we need to trace the autograd graph when training.

**Comment by twmht** [comment]
@HIT-cwh 

Well, I found out it also works by commenting out all the backward and step when training object detection, No OOM happens. 

It's weird since the consuming memory is almost the same as when doing normal object detection training.

My pytorch version is 1.9. 

What is your batch size and number of gpus when training with ImageNet?

**Comment by pppppM** [comment]
Samples_per_gpu=8 and GPUS=8
