### ISSUE TITLE
[Bug] Default process group has not been initialized with autoslim search

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmrazor#74]
I tried to search subnets from supernet with autoslim.

```
python ./tools/mmcls/search_mmcls.py \
  configs/pruning/autoslim/autoslim_mbv2_search_8xb1024_in1k.py \
  your_pre-training_checkpoint_path \
  --work-dir your_work_dir
```

![image](https://user-images.githubusercontent.com/1567200/153328846-0c12abe8-e071-46b9-a9ba-5473afb63ba5.png)

Do I need to use distributed mode when searching?

**Comment by HIT-cwh** [comment]
Thank you for your issue. 
At present, distributed mode is needed when searching even if only one gpu is used. It is hacky and we are refactoring the search part. The new version will no longer have this problem.

**Comment by tanghy2016** [comment]
这个问题现在的版本解决了吗？我也遇到一样的问题

**Comment by HIT-cwh** [comment]
You can avoid this by trying distributed mode.

Plus, using English is more appreciated for better community discussion around the world.

**Comment by tanghy2016** [comment]
where to do the setup you said

**Comment by HIT-cwh** [comment]
> where to do the setup you said

You can set the job launcher to one of ``pytorch``, ``slurm`` or ``mpi`` (ref to [here](https://github.com/open-mmlab/mmrazor/blob/e4e95131a2451f748923fe702c269d02c9a753f6/tools/mmcls/search_mmcls.py#L52-L56) ) to use distributed mode.

**Comment by tanghy2016** [comment]
```
$ python ./tools/mmcls/search_mmcls.py \
>   configs/pruning/autoslim/autoslim_mbv2_search_8xb1024_ci10.py \
>   output/epoch_50.pth \
>   --work-dir output \
>   --launcher pytorch
/home/tanghuayang/venv_torch/lib/python3.6/site-packages/mmrazor/utils/setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting OMP_NUM_THREADS environment variable for each process '
/home/tanghuayang/venv_torch/lib/python3.6/site-packages/mmrazor/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
  f'Setting MKL_NUM_THREADS environment variable for each process '
Traceback (most recent call last):
  File "./tools/mmcls/search_mmcls.py", line 181, in <module>
    main()
  File "./tools/mmcls/search_mmcls.py", line 99, in main
    init_dist(args.launcher, **cfg.dist_params)
  File "/home/tanghuayang/venv_torch/lib64/python3.6/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
    _init_dist_pytorch(backend, **kwargs)
  File "/home/tanghuayang/venv_torch/lib64/python3.6/site-packages/mmcv/runner/dist_utils.py", line 29, in _init_dist_pytorch
    rank = int(os.environ['RANK'])
  File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'
```

Is it necessary to configure cfg.dist_params? And, how to configure it?

**Comment by tanghy2016** [comment]
> ```
> $ python ./tools/mmcls/search_mmcls.py \
> >   configs/pruning/autoslim/autoslim_mbv2_search_8xb1024_ci10.py \
> >   output/epoch_50.pth \
> >   --work-dir output \
> >   --launcher pytorch
> /home/tanghuayang/venv_torch/lib/python3.6/site-packages/mmrazor/utils/setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
>   f'Setting OMP_NUM_THREADS environment variable for each process '
> /home/tanghuayang/venv_torch/lib/python3.6/site-packages/mmrazor/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
>   f'Setting MKL_NUM_THREADS environment variable for each process '
> Traceback (most recent call last):
>   File "./tools/mmcls/search_mmcls.py", line 181, in <module>
>     main()
>   File "./tools/mmcls/search_mmcls.py", line 99, in main
>     init_dist(args.launcher, **cfg.dist_params)
>   File "/home/tanghuayang/venv_torch/lib64/python3.6/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
>     _init_dist_pytorch(backend, **kwargs)
>   File "/home/tanghuayang/venv_torch/lib64/python3.6/site-packages/mmcv/runner/dist_utils.py", line 29, in _init_dist_pytorch
>     rank = int(os.environ['RANK'])
>   File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'RANK'
> ```
> 
> Is it necessary to configure cfg.dist_params? And, how to configure it?

it's runing, use the following command:
```
$ RANK=0 WORLD_SIZE=1 MASTER_ADDR=127.0.0.1 MASTER_PORT=1692 python ./tools/mmcls/search_mmcls.py \
  configs/pruning/autoslim/autoslim_mbv2_search_8xb1024_ci10.py \
  output/epoch_50.pth \
  --work-dir output \
  --launcher pytorch
```

**Comment by tanghy2016** [comment]
> > ```
> > $ python ./tools/mmcls/search_mmcls.py \
> > >   configs/pruning/autoslim/autoslim_mbv2_search_8xb1024_ci10.py \
> > >   output/epoch_50.pth \
> > >   --work-dir output \
> > >   --launcher pytorch
> > /home/tanghuayang/venv_torch/lib/python3.6/site-packages/mmrazor/utils/setup_env.py:33: UserWarning: Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> >   f'Setting OMP_NUM_THREADS environment variable for each process '
> > /home/tanghuayang/venv_torch/lib/python3.6/site-packages/mmrazor/utils/setup_env.py:43: UserWarning: Setting MKL_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> >   f'Setting MKL_NUM_THREADS environment variable for each process '
> > Traceback (most recent call last):
> >   File "./tools/mmcls/search_mmcls.py", line 181, in <module>
> >     main()
> >   File "./tools/mmcls/search_mmcls.py", line 99, in main
> >     init_dist(args.launcher, **cfg.dist_params)
> >   File "/home/tanghuayang/venv_torch/lib64/python3.6/site-packages/mmcv/runner/dist_utils.py", line 18, in init_dist
> >     _init_dist_pytorch(backend, **kwargs)
> >   File "/home/tanghuayang/venv_torch/lib64/python3.6/site-packages/mmcv/runner/dist_utils.py", line 29, in _init_dist_pytorch
> >     rank = int(os.environ['RANK'])
> >   File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
> >     raise KeyError(key) from None
> > KeyError: 'RANK'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is it necessary to configure cfg.dist_params? And, how to configure it?
> 
> it's runing, use the following command:
> 
> ```
> $ RANK=0 WORLD_SIZE=1 MASTER_ADDR=127.0.0.1 MASTER_PORT=1692 python ./tools/mmcls/search_mmcls.py \
>   configs/pruning/autoslim/autoslim_mbv2_search_8xb1024_ci10.py \
>   output/epoch_50.pth \
>   --work-dir output \
>   --launcher pytorch
> ```

but, how to write these configuration parameters into cfg.dist_params?
