### ISSUE TITLE
Why not recalibrate BN stats with autoslim?

### ISSUE THREAD

**Issue by twmht** [open-mmlab/mmrazor#75]
Hi,

I found out the original implementation recalibrate BN stats after training.

https://github.com/JiahuiYu/slimmable_networks/blob/5dc14d0357ccfc596d706281acdc8a5b0b66c6d6/models/slimmable_ops.py#L204
https://github.com/JiahuiYu/slimmable_networks/blob/master/train.py#L758

But in mmrazor you don't do that but still get a good result

> We do not recalibrating BN statistics after training

 this is not consistent with the paper.

any idea? is recalibration not necessary?

**Comment by HIT-cwh** [comment]
Recalibration may be unnecessary when ``SwitchableBatchNorm`` is used.
